<?php
return [
	//ARGENTINA
			[
					'name' => 'Buenos Aires',
					'region' => 'BA',
					'country' => 'AR',
					'latitude' => '-34.61178',
					'longitude' => '-58.41731',
			],
			[
					'name' => 'Córdoba',
					'region' => 'CB',
					'country' => 'AR',
					'latitude' => '-31.41350',
					'longitude' => '-64.18105',
			],
			[
					'name' => 'Rosario',
					'region' => 'SF',
					'country' => 'AR',
					'latitude' => '-32.95113',
					'longitude' => '-60.62116',
			],
			[
					'name' => 'Mendoza',
					'region' => 'MZA',
					'country' => 'AR',
					'latitude' => '-32.89084',
					'longitude' => '-68.82717',
			],
			[
					'name' => 'San Juan',
					'region' => 'SJ',
					'country' => 'AR',
					'latitude' => '-31.53750',
					'longitude' => '-68.53639',
			],
			[
					'name' => 'Tucumán',
					'region' => 'T',
					'country' => 'AR',
					'latitude' => '-26.80828',
					'longitude' => '-65.21759',
			],
			[
					'name' => 'Salta',
					'region' => 'A',
					'country' => 'AR',
					'latitude' => '-24.78835',
					'longitude' => '-65.41266',
			],
			[
					'name' => 'La Plata',
					'region' => 'BA',
					'country' => 'AR',
					'latitude' => '-34.92049',
					'longitude' => '-57.95356',
			],
			[
					'name' => 'Mar del Plata',
					'region' => 'BA',
					'country' => 'AR',
					'latitude' => '-38.00547',
					'longitude' => '-57.54261',
			],
			[
					'name' => 'San Miguel de Tucumán',
					'region' => 'T',
					'country' => 'AR',
					'latitude' => '-26.81590',
					'longitude' => '-65.22362',
			],
			[
					'name' => 'La Matanza',
					'region' => 'BA',
					'country' => 'AR',
					'latitude' => '-34.76118',
					'longitude' => '-58.63119',
			],
			[
					'name' => 'San Salvador de Jujuy',
					'region' => 'J',
					'country' => 'AR',
					'latitude' => '-24.18571',
					'longitude' => '-65.29926',
			],
			[
					'name' => 'Corrientes',
					'region' => 'W',
					'country' => 'AR',
					'latitude' => '-27.46758',
					'longitude' => '-58.83411',
			],
			[
					'name' => 'Posadas',
					'region' => 'N',
					'country' => 'AR',
					'latitude' => '-27.36214',
					'longitude' => '-55.90088',
			],
			[
					'name' => 'Santiago del Estero',
					'region' => 'G',
					'country' => 'AR',
					'latitude' => '-27.79511',
					'longitude' => '-64.26149',
			],
			[
					'name' => 'Merlo',
					'region' => 'BA',
					'country' => 'AR',
					'latitude' => '-34.66408',
					'longitude' => '-58.70031',
			],
	//COLOMBIA
	[
			'name' => 'Bogotá',
			'region' => 'DC',
			'country' => 'CO',
			'latitude' => '4.60971',
			'longitude' => '-74.08175',
	],
	[
			'name' => 'Medellín',
			'region' => 'ANT',
			'country' => 'CO',
			'latitude' => '6.24420',
			'longitude' => '-75.58118',
	],
	[
			'name' => 'Cali',
			'region' => 'VCA',
			'country' => 'CO',
			'latitude' => '3.43722',
			'longitude' => '-76.52250',
	],
	[
			'name' => 'Barranquilla',
			'region' => 'ATL',
			'country' => 'CO',
			'latitude' => '10.96389',
			'longitude' => '-74.79666',
	],
	[
			'name' => 'Cartagena',
			'region' => 'BOL',
			'country' => 'CO',
			'latitude' => '10.39972',
			'longitude' => '-75.51444',
	],
	[
			'name' => 'Cúcuta',
			'region' => 'NDS',
			'country' => 'CO',
			'latitude' => '7.89389',
			'longitude' => '-72.50777',
	],
	[
			'name' => 'Bucaramanga',
			'region' => 'SAN',
			'country' => 'CO',
			'latitude' => '7.12539',
			'longitude' => '-73.11980',
	],
	[
			'name' => 'Pereira',
			'region' => 'RIS',
			'country' => 'CO',
			'latitude' => '4.81333',
			'longitude' => '-75.69611',
	],
	[
			'name' => 'Santa Marta',
			'region' => 'MAG',
			'country' => 'CO',
			'latitude' => '11.24722',
			'longitude' => '-74.20056',
	],
	[
			'name' => 'Manizales',
			'region' => 'CAL',
			'country' => 'CO',
			'latitude' => '5.06889',
			'longitude' => '-75.51861',
	],
	[
			'name' => 'Ibagué',
			'region' => 'TOL',
			'country' => 'CO',
			'latitude' => '4.43889',
			'longitude' => '-75.23222',
	],
	[
			'name' => 'Villavicencio',
			'region' => 'MET',
			'country' => 'CO',
			'latitude' => '4.13489',
			'longitude' => '-73.62692',
	],
	[
			'name' => 'Pasto',
			'region' => 'NAR',
			'country' => 'CO',
			'latitude' => '1.21361',
			'longitude' => '-77.28111',
	],
	[
			'name' => 'Neiva',
			'region' => 'HUI',
			'country' => 'CO',
			'latitude' => '2.92729',
			'longitude' => '-75.28189',
	],
	[
			'name' => 'Armenia',
			'region' => 'QUI',
			'country' => 'CO',
			'latitude' => '4.53444',
			'longitude' => '-75.67583',
	],
	[
			'name' => 'Popayán',
			'region' => 'CAU',
			'country' => 'CO',
			'latitude' => '2.43861',
			'longitude' => '-76.61694',
	],
	[
			'name' => 'Sincelejo',
			'region' => 'SUC',
			'country' => 'CO',
			'latitude' => '9.30472',
			'longitude' => '-75.39778',
	],
	[
			'name' => 'Tunja',
			'region' => 'BOY',
			'country' => 'CO',
			'latitude' => '5.53528',
			'longitude' => '-73.36778',
	],
	[
			'name' => 'Valledupar',
			'region' => 'CES',
			'country' => 'CO',
			'latitude' => '10.46314',
			'longitude' => '-73.25322',
	],
	[
			'name' => 'Montería',
			'region' => 'COR',
			'country' => 'CO',
			'latitude' => '8.74798',
			'longitude' => '-75.88173',
	],
	[
			'name' => 'Palmira',
			'region' => 'VCA',
			'country' => 'CO',
			'latitude' => '3.53722',
			'longitude' => '-76.30333',
	],
	[
			'name' => 'Soledad',
			'region' => 'ATL',
			'country' => 'CO',
			'latitude' => '10.91890',
			'longitude' => '-74.76493',
	],
	[
			'name' => 'Bello',
			'region' => 'ANT',
			'country' => 'CO',
			'latitude' => '6.33694',
			'longitude' => '-75.56472',
	],
	[
			'name' => 'Floridablanca',
			'region' => 'SAN',
			'country' => 'CO',
			'latitude' => '7.06722',
			'longitude' => '-73.08694',
	],
	[
			'name' => 'Envigado',
			'region' => 'ANT',
			'country' => 'CO',
			'latitude' => '6.16944',
			'longitude' => '-75.58278',
	],
	[
			'name' => 'Tuluá',
			'region' => 'VCA',
			'country' => 'CO',
			'latitude' => '4.08667',
			'longitude' => '-76.19528',
	],
	[
			'name' => 'Villamaria',
			'region' => 'CAL',
			'country' => 'CO',
			'latitude' => '4.41306',
			'longitude' => '-75.20694',
	],
	[
			'name' => 'Piedecuesta',
			'region' => 'SAN',
			'country' => 'CO',
			'latitude' => '6.99806',
			'longitude' => '-73.04833',
	],
	[
			'name' => 'Tumaco',
			'region' => 'NAR',
			'country' => 'CO',
			'latitude' => '1.79861',
			'longitude' => '-78.98306',
	],
	[
			'name' => 'Mocoa',
			'region' => 'PUT',
			'country' => 'CO',
			'latitude' => '1.14917',
			'longitude' => '-76.63111',
	],
	[
			'name' => 'Ocaña',
			'region' => 'NDS',
			'country' => 'CO',
			'latitude' => '8.23806',
			'longitude' => '-73.35611',
	],
	[
			'name' => 'Quibdó',
			'region' => 'CHO',
			'country' => 'CO',
			'latitude' => '5.69278',
			'longitude' => '-76.65806',
	],
	[
			'name' => 'Arauca',
			'region' => 'ARA',
			'country' => 'CO',
			'latitude' => '7.08472',
			'longitude' => '-70.75556',
	],
	[
			'name' => 'Magangué',
			'region' => 'BOL',
			'country' => 'CO',
			'latitude' => '9.23972',
			'longitude' => '-74.75306',
	],
	[
			'name' => 'Leticia',
			'region' => 'AMZ',
			'country' => 'CO',
			'latitude' => '-4.20417',
			'longitude' => '-69.93472',
	],
	[
			'name' => 'Yopal',
			'region' => 'CAS',
			'country' => 'CO',
			'latitude' => '5.33611',
			'longitude' => '-72.39583',
	],
	[
			'name' => 'Arauquita',
			'region' => 'ARA',
			'country' => 'CO',
			'latitude' => '7.03778',
			'longitude' => '-70.76083',
	],
	[
			'name' => 'Santander de Quilichao',
			'region' => 'CAU',
			'country' => 'CO',
			'latitude' => '3.01444',
			'longitude' => '-76.48528',
	],
	[
			'name' => 'Girardot',
			'region' => 'CUN',
			'country' => 'CO',
			'latitude' => '4.30361',
			'longitude' => '-74.80667',
	],
	[
			'name' => 'Túquerres',
			'region' => 'NAR',
			'country' => 'CO',
			'latitude' => '1.08611',
			'longitude' => '-77.62667',
	],
	[
			'name' => 'Espinal',
			'region' => 'TOL',
			'country' => 'CO',
			'latitude' => '4.15444',
			'longitude' => '-74.88722',
	],
	[
			'name' => 'Mocoa',
			'region' => 'PUT',
			'country' => 'CO',
			'latitude' => '1.14917',
			'longitude' => '-76.63111',
	],
	[
			'name' => 'Ocaña',
			'region' => 'NDS',
			'country' => 'CO',
			'latitude' => '8.23806',
			'longitude' => '-73.35611',
	],
	//MEXICO
	
	[
			'name' => 'Mexico City',
			'state' => 'CMX',
			'country' => 'MX',
			'latitude' => '19.43261',
			'longitude' => '-99.13321',
	],
	[
			'name' => 'Guadalajara',
			'state' => 'JAL',
			'country' => 'MX',
			'latitude' => '20.65970',
			'longitude' => '-103.34961',
	],
	[
			'name' => 'Monterrey',
			'state' => 'NLE',
			'country' => 'MX',
			'latitude' => '25.67100',
			'longitude' => '-100.30997',
	],
	[
			'name' => 'Puebla',
			'state' => 'PUE',
			'country' => 'MX',
			'latitude' => '19.04144',
			'longitude' => '-98.20627',
	],
	[
			'name' => 'Guadalupe',
			'state' => 'NLE',
			'country' => 'MX',
			'latitude' => '25.67694',
			'longitude' => '-100.25306',
	],
	[
			'name' => 'Tijuana',
			'state' => 'BCN',
			'country' => 'MX',
			'latitude' => '32.51495',
			'longitude' => '-117.03825',
	],
	[
			'name' => 'León',
			'state' => 'GUA',
			'country' => 'MX',
			'latitude' => '21.12222',
			'longitude' => '-101.67278',
	],
	[
			'name' => 'Zapopan',
			'state' => 'JAL',
			'country' => 'MX',
			'latitude' => '20.72354',
			'longitude' => '-103.38486',
	],
	[
			'name' => 'Naucalpan',
			'state' => 'MEX',
			'country' => 'MX',
			'latitude' => '19.47940',
			'longitude' => '-99.23308',
	],
	[
			'name' => 'Merida',
			'state' => 'YUC',
			'country' => 'MX',
			'latitude' => '20.96759',
			'longitude' => '-89.59277',
	],
	[
			'name' => 'Ciudad Juárez',
			'state' => 'CHH',
			'country' => 'MX',
			'latitude' => '31.73416',
			'longitude' => '-106.46031',
	],
	[
			'name' => 'Hermosillo',
			'state' => 'SON',
			'country' => 'MX',
			'latitude' => '29.07297',
			'longitude' => '-110.95592',
	],
	[
			'name' => 'Saltillo',
			'state' => 'COA',
			'country' => 'MX',
			'latitude' => '25.43880',
			'longitude' => '-100.97367',
	],
	[
			'name' => 'Mexicali',
			'state' => 'BCN',
			'country' => 'MX',
			'latitude' => '32.62781',
			'longitude' => '-115.45446',
	],
	[
			'name' => 'San Luis Potosí',
			'state' => 'SLP',
			'country' => 'MX',
			'latitude' => '22.14982',
			'longitude' => '-100.97986',
	],
	[
			'name' => 'Aguascalientes',
			'state' => 'AGU',
			'country' => 'MX',
			'latitude' => '21.88091',
			'longitude' => '-102.29579',
	],
	[
			'name' => 'Querétaro',
			'state' => 'QRO',
			'country' => 'MX',
			'latitude' => '20.58806',
			'longitude' => '-100.38917',
	],
	[
			'name' => 'Morelia',
			'state' => 'MOR',
			'country' => 'MX',
			'latitude' => '19.70078',
			'longitude' => '-101.18443',
	],
	[
			'name' => 'Tlalnepantla',
			'state' => 'MEX',
			'country' => 'MX',
			'latitude' => '19.53778',
			'longitude' => '-99.19222',
	],
	[
			'name' => 'Cancún',
			'state' => 'ROO',
			'country' => 'MX',
			'latitude' => '21.17429',
			'longitude' => '-86.84656',
	],
	[
			'name' => 'Cuernavaca',
			'state' => 'MOR',
			'country' => 'MX',
			'latitude' => '18.92421',
			'longitude' => '-99.22244',
	],
	[
			'name' => 'Toluca',
			'state' => 'MEX',
			'country' => 'MX',
			'latitude' => '19.29278',
			'longitude' => '-99.65616',
	],
	[
			'name' => 'Chihuahua',
			'state' => 'CHH',
			'country' => 'MX',
			'latitude' => '28.63528',
			'longitude' => '-106.08889',
	],
	[
			'name' => 'Torreón',
			'state' => 'COA',
			'country' => 'MX',
			'latitude' => '25.54276',
			'longitude' => '-103.40673',
	],
	[
			'name' => 'Victoria',
			'state' => 'TAM',
			'country' => 'MX',
			'latitude' => '23.73692',
			'longitude' => '-99.14111',
	],
	[
			'name' => 'Durango',
			'state' => 'DUR',
			'country' => 'MX',
			'latitude' => '24.02772',
			'longitude' => '-104.65317',
	],
	[
			'name' => 'Ciudad López Mateos',
			'state' => 'MEX',
			'country' => 'MX',
			'latitude' => '19.55416',
			'longitude' => '-99.26194',
	],
	[
			'name' => 'San Nicolás de los Garza',
			'state' => 'NLE',
			'country' => 'MX',
			'latitude' => '25.74923',
			'longitude' => '-100.28949',
	],
	[
			'name' => 'Reynosa',
			'state' => 'TAM',
			'country' => 'MX',
			'latitude' => '26.07950',
			'longitude' => '-98.28835',
	]
];